#!/bin/bash

sleep 0
echo '
Gobuster v1.3                OJ Reeves (@TheColonial)
=====================================================
[+] Mode         : dir
[+] Url/Domain   : http://192.168.56.3/
[+] Threads      : 10
[+] Wordlist     : Documents/tools/Seclists/Discovery/Web_Content/raft-medium-directories.txt
[+] Status codes : 204,301,302,307,200
=====================================================
/test (Status: 301)
/phpMyAdmin (Status: 301)
/index (Status: 200)
/twiki (Status: 301)
/phpinfo (Status: 200)
/dav (Status: 301)
/tikiwiki (Status: 301)
/this_is_just_test_output (Status: 420)
=====================================================
'
